/**
 * url-shortener
 * This is a URL shortener API.
 *
 * OpenAPI spec version: 1.0
 * Contact: vadim.uvin2@swisscom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UrlAnalyticsItem } from './urlAnalyticsItem';

/**
 * Full URL to be displayed in URL details
 */
export interface Url {
    id: string;
    shortUrl: string;
    fullUrl: string;
    analytics?: Array<UrlAnalyticsItem>;
}
