/**
 * url-shortener
 * This is a URL shortener API.
 *
 * OpenAPI spec version: 1.0
 * Contact: vadim.uvin2@swisscom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Contains how many clicks some URL had at a given date and time
 */
export interface UrlAnalyticsItem { 
    datetime: Date;
    /**
     * how many times a URL was clicked
     */
    clicked: number;
}