/**
 * url-shortener
 * This is a URL shortener API.
 *
 * OpenAPI spec version: 1.0
 * Contact: vadim.uvin2@swisscom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * URL data without analytics to show in a list
 */
export interface UrlItem { 
    id?: string;
    shortUrl?: string;
    fullUrl?: string;
}